name: Deploy on Server
on:
  push:
    branches:
      - dev


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy 
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            cd ~/.ssh
            chmod 600 id_rsa
            scp cowsay ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER }}:~/
            ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER }} 'sudo systemctl restart cowsay-service'
